### PR TITLE
Update catalogue files

### LINKED ISSUE #180: updated catalog files for results page
Hi!
We found some issues during proofing at the journal with our catalogs, where we did not clean-up a special kind of duplicates properly.
This has been cleaned up now, and we created a v1.1 of all result catalog files, that should be replaced on planetfour.org/results.
The recent "Raw data" and "Intermediate data products" have not been changed.

Here's a link to the zip file with all other files:

https://www.dropbox.com/s/9hb7sw5a5zxt45z/P4_catalog_v1.1.zip?dl=1

Thanks!

### PR DESCRIPTION
**Pull request by adammcmaster**
Closes #180

### CODE REVIEW

**Comment by michaelaye** [comment]
oh, they are submitted as supplementary files already with the paper, not sure if we want them on here, @mschwamb what do you think?

**Comment by michaelaye** [comment]
The links look good to me.

**Comment by mschwamb** [comment]
Thanks. If it's not too much trouble maybe we should include them as well. But it can be a separate commit later if that's helpful

**Comment by mschwamb** [comment]
This can be committed as is

**Comment by adammcmaster** [comment]
OK, this is deployed now. If you can open an issue with the web page text for the other files I'll add the links.

**Pull request merged**
